
version: '3.9'

services:
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db
    restart: unless-stopped
    networks:
      local:
      
networks:
  local:
  
volumes:
  mongo-db-data:
  
